# Generated by Django 5.2.15 on 2026-07-24 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('tier', models.CharField(choices=[('small', 'Small (50-500)'), ('medium', 'Medium (500-5,000)'), ('large', 'Large / Institutional')], default='small', max_length=10)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('min_members', models.PositiveIntegerField(default=0)),
                ('max_members', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price_monthly', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('psp', 'Payments'), ('sms', 'SMS / USSD'), ('email', 'Email'), ('other', 'Other')], default='other', max_length=10)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('down', 'Down')], default='operational', max_length=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'provider statuses',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('dns_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('ssl_status', models.CharField(choices=[('awaiting', 'Awaiting'), ('issued', 'Issued'), ('failed', 'Failed')], default='awaiting', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.cooperative')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect_name', models.CharField(blank=True, help_text='Used before a Cooperative record exists.', max_length=200)),
                ('stage', models.CharField(choices=[('discovery', 'Discovery'), ('data_migration', 'Data migration'), ('parallel_run', 'Parallel run'), ('go_live', 'Go-live'), ('done', 'Completed')], default='discovery', max_length=20)),
                ('target_go_live', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_items', to='tenants.cooperative')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_onboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('onboarding_lead', 'Onboarding lead'), ('support', 'Support'), ('finance', 'Finance')], default='support', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_team_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='trial', max_length=10)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('cooperative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.cooperative')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='platform_admin.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('period_label', models.CharField(blank=True, help_text="e.g. 'Jun 2026'", max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void')], default='draft', max_length=10)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.cooperative')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='platform_admin.subscription')),
            ],
            options={
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
    ]
