# Generated by Django 5.2.15 on 2026-07-25 21:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0002_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('down', 'Down')], max_length=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='platform_admin.providerstatus')),
            ],
            options={
                'ordering': ['checked_at'],
            },
        ),
    ]
