# Generated by Django 5.2.15 on 2026-07-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0003_incident_providercheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-app')], default='email', max_length=8)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, help_text='Supports {{placeholders}} like {{coop_name}}, {{amount}}.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Startup Ripple', max_length=120)),
                ('brand_color', models.CharField(default='#0b4f3a', max_length=7)),
                ('support_email', models.EmailField(default='support@cooperativeos.africa', max_length=254)),
                ('default_currency', models.CharField(default='NGN', max_length=3)),
                ('default_timezone', models.CharField(default='Africa/Lagos', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
