# Generated by Django 5.2.15 on 2026-09-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0004_notificationtemplate_platformprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Square mark for the browser tab.', null=True, upload_to='platform_brand/'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text="The platform's own mark, used where no cooperative brand applies (sign-in, platform console, default emails).", null=True, upload_to='platform_brand/'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
