# Generated by Django 5.2.15 on 2026-09-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0005_platformprofile_favicon_platformprofile_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_eyebrow', models.CharField(default='Built for cooperatives and credit unions of 50–5,000 members', help_text='The small pill of text above the headline.', max_length=160)),
                ('hero_title', models.CharField(default='A digital operating layer for cooperatives everywhere.', help_text='The main headline. Keep it to one sentence.', max_length=200)),
                ('hero_subtitle', models.TextField(default='Membership, contributions, loans, governance and audit-ready reporting — in one place, on an append-only double-entry ledger your auditor can actually follow.', help_text='The paragraph under the headline.')),
                ('hero_primary_cta', models.CharField(default='Get started', max_length=40)),
                ('hero_secondary_cta', models.CharField(default='Sign in to your society', max_length=40)),
                ('hero_image', models.ImageField(blank=True, help_text='A wide photograph beside the headline. Landscape, at least 1200px wide. Leave empty to show a plain panel instead.', null=True, upload_to='site_content/')),
                ('hero_image_alt', models.CharField(blank=True, help_text="Describes the image for screen readers and when it fails to load. e.g. 'Members of a savings group meeting'.", max_length=200)),
                ('principle_eyebrow', models.CharField(default='Our core principle', max_length=80)),
                ('principle_title', models.CharField(default='Ledger, not custodian.', max_length=120)),
                ('principle_body', models.TextField(default="Money moves through licensed payment providers into your society's own bank account. We record, reconcile and report on it — we never hold member funds in a platform wallet. That is a deliberate engineering and regulatory choice, and it is why your money never depends on us staying solvent.")),
                ('features_title', models.CharField(default='Everything a society runs on', max_length=120)),
                ('features_intro', models.TextField(default='Replacing the member register, the contribution book and the annual scramble to produce accounts.')),
                ('steps_title', models.CharField(default='How it works', max_length=120)),
                ('gallery_title', models.CharField(default='Built for the people who run cooperatives', help_text='Heading above the photo strip.', max_length=120)),
                ('gallery_intro', models.TextField(blank=True, default='Treasurers, secretaries and members — the people who keep a society running, wherever it is.')),
                ('pricing_title', models.CharField(default='Pricing that follows your size', max_length=120)),
                ('pricing_intro', models.TextField(default="A monthly subscription per society — not a cut of your members' money.")),
                ('pricing_fallback', models.TextField(default="Pricing depends on your society's size and how much history needs migrating.", help_text="Shown when no plans are published yet. The 'talk to us' link is added automatically.")),
                ('footer_tagline', models.CharField(default='by Startup Ripple', max_length=120)),
                ('footer_disclaimer', models.TextField(default='CooperativeOS records and reports on cooperative finances. It is not a bank, a lender, or a deposit-taking institution, and it does not hold member funds.', help_text='Legal footnote at the very bottom. Changing this may have regulatory consequences — check before editing.')),
                ('meta_title', models.CharField(blank=True, help_text='Browser tab and search-result title. Under 60 characters is best. Leave empty to use the platform name.', max_length=70)),
                ('meta_description', models.CharField(blank=True, default='Membership, contributions, loans and audit-ready reporting for cooperatives, on an append-only ledger.', help_text='The grey text under the title in search results.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site content',
            },
        ),
        migrations.CreateModel(
            name='SiteFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('visible', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting it.')),
                ('icon', models.CharField(choices=[('group', 'People'), ('savings', 'Savings'), ('request_quote', 'Loan / quote'), ('how_to_vote', 'Voting'), ('summarize', 'Reports'), ('campaign', 'Announcements'), ('account_balance', 'Bank'), ('receipt_long', 'Receipts'), ('verified_user', 'Security'), ('lock', 'Lock'), ('insights', 'Insights'), ('handshake', 'Partnership'), ('payments', 'Payments'), ('schedule', 'Time'), ('support_agent', 'Support'), ('cloud_done', 'Cloud'), ('fact_check', 'Audit'), ('diversity_3', 'Community')], default='group', max_length=40)),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Site feature card',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('visible', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting it.')),
                ('image', models.ImageField(help_text='Landscape, at least 800px wide. Photographs of real people work far better here than stock illustrations.', upload_to='site_content/')),
                ('alt_text', models.CharField(help_text='Describes the photo for screen readers. Required.', max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Optional line shown under the photo.', max_length=120)),
            ],
            options={
                'verbose_name': 'Site gallery photo',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('visible', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting it.')),
                ('number', models.CharField(help_text='Shown above the step, e.g. 01.', max_length=4)),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Site how-it-works step',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteTrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('visible', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting it.')),
                ('text', models.CharField(max_length=120)),
                ('icon', models.CharField(choices=[('group', 'People'), ('savings', 'Savings'), ('request_quote', 'Loan / quote'), ('how_to_vote', 'Voting'), ('summarize', 'Reports'), ('campaign', 'Announcements'), ('account_balance', 'Bank'), ('receipt_long', 'Receipts'), ('verified_user', 'Security'), ('lock', 'Lock'), ('insights', 'Insights'), ('handshake', 'Partnership'), ('payments', 'Payments'), ('schedule', 'Time'), ('support_agent', 'Support'), ('cloud_done', 'Cloud'), ('fact_check', 'Audit'), ('diversity_3', 'Community')], default='verified_user', max_length=40)),
            ],
            options={
                'verbose_name': 'Site trust badge',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
