# Generated by Django 5.2.15 on 2026-09-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0007_seed_site_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('visible', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting it.')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(help_text='Two or three sentences.')),
                ('bullets', models.TextField(blank=True, help_text='One per line. Shown as a ticked list under the text. Leave empty for none.')),
                ('image', models.ImageField(blank=True, help_text='Landscape, at least 1000px wide. Until one is uploaded the block shows a plain panel in its place.', null=True, upload_to='site_content/')),
                ('image_alt', models.CharField(blank=True, help_text='Describes the photo for screen readers.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site feature deep-dive',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='android_apk',
            field=models.FileField(blank=True, help_text="Or upload the APK directly for side-loading. If a Play Store link is set above, that is used instead. Large uploads can hit the host's file-size limit — upload over SFTP and link to it if the admin times out.", null=True, upload_to='site_apps/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='android_store_url',
            field=models.URLField(blank=True, help_text='Google Play link. Leave empty if not published there yet.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='app_screenshot',
            field=models.ImageField(blank=True, help_text='A phone screenshot beside the download buttons. Portrait.', null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='app_screenshot_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='apps_body',
            field=models.TextField(default='Members check their contributions, savings and loan balance, read statements and get notices — without calling the secretary. Officers can approve from the same app.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='apps_note',
            field=models.CharField(blank=True, help_text="Small line under the buttons, e.g. 'iOS version coming soon'. Leave empty to hide it.", max_length=160),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='apps_title',
            field=models.CharField(default="Put it in your members' hands", max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='cta_body',
            field=models.TextField(default='Tell us about your society and we will talk through what needs migrating. Nothing is charged until you decide to go ahead.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='cta_button',
            field=models.CharField(default='Apply as a society', max_length=40),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='cta_image',
            field=models.ImageField(blank=True, help_text='Optional photograph behind the closing banner. A wide, fairly dark image works best — text sits on top of it.', null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='cta_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='cta_title',
            field=models.CharField(default='Ready to bring your society on board?', max_length=160),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='ios_store_url',
            field=models.URLField(blank=True, help_text='App Store link. Leave empty to hide the iOS button.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='showcase_intro',
            field=models.TextField(blank=True, default='The parts of running a society that take the most time, and what replaces them.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='showcase_title',
            field=models.CharField(default='A closer look at the day-to-day', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='steps_intro',
            field=models.TextField(blank=True, default='From your first conversation with us to members checking their own statements — usually six to ten weeks.'),
        ),
        migrations.AddField(
            model_name='sitestep',
            name='icon',
            field=models.CharField(choices=[('group', 'People'), ('savings', 'Savings'), ('request_quote', 'Loan / quote'), ('how_to_vote', 'Voting'), ('summarize', 'Reports'), ('campaign', 'Announcements'), ('account_balance', 'Bank'), ('receipt_long', 'Receipts'), ('verified_user', 'Security'), ('lock', 'Lock'), ('insights', 'Insights'), ('handshake', 'Partnership'), ('payments', 'Payments'), ('schedule', 'Time'), ('support_agent', 'Support'), ('cloud_done', 'Cloud'), ('fact_check', 'Audit'), ('diversity_3', 'Community')], default='handshake', help_text='Shown in the diagram above the steps.', max_length=40),
        ),
    ]
