# Generated by Django 5.2.15 on 2026-09-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0009_seed_site_showcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='cta_body',
            field=models.TextField(default='Tell us about your cooperative and we will talk through what needs migrating. Nothing is charged until you decide to go ahead.'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='cta_button',
            field=models.CharField(default='Apply as a cooperative', max_length=40),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='cta_title',
            field=models.CharField(default='Ready to bring your cooperative on board?', max_length=160),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='features_title',
            field=models.CharField(default='Everything a cooperative runs on', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='gallery_intro',
            field=models.TextField(blank=True, default='Treasurers, secretaries and members — the people who keep a cooperative running, wherever it is.'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_secondary_cta',
            field=models.CharField(default='Sign in to your cooperative', max_length=40),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='pricing_fallback',
            field=models.TextField(default="Pricing depends on your cooperative's size and how much history needs migrating.", help_text="Shown when no plans are published yet. The 'talk to us' link is added automatically."),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='pricing_intro',
            field=models.TextField(default="A monthly subscription per cooperative — not a cut of your members' money."),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='principle_body',
            field=models.TextField(default="Money moves through licensed payment providers into your cooperative's own bank account. We record, reconcile and report on it — we never hold member funds in a platform wallet. That is a deliberate engineering and regulatory choice, and it is why your money never depends on us staying solvent."),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='showcase_intro',
            field=models.TextField(blank=True, default='The parts of running a cooperative that take the most time, and what replaces them.'),
        ),
    ]
