# Generated by Django 5.2.15 on 2026-09-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0011_rename_society_to_cooperative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='cta_image',
            field=models.ImageField(blank=True, help_text='Photograph behind the closing banner. A wide, fairly dark image works best — text sits on top of it. Leave empty to use the built-in default.', null=True, upload_to='site_content/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='A wide photograph beside the headline. Landscape, at least 1200px wide. Leave empty to use the built-in default photograph.', null=True, upload_to='site_content/'),
        ),
        migrations.AlterField(
            model_name='siteshowcase',
            name='image',
            field=models.ImageField(blank=True, help_text='Landscape, at least 1000px wide. Leave empty and the block falls back to one of the built-in default photographs.', null=True, upload_to='site_content/'),
        ),
    ]
