# Generated by Django 5.2.15 on 2026-09-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0012_alter_sitecontent_cta_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformprofile',
            name='support_email',
            field=models.EmailField(default='info@mycooperativeos.com', max_length=254),
        ),
    ]
