# Generated by Django 5.2.15 on 2026-09-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0014_update_support_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingitem',
            name='golive_email_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the go-live announcement was last sent to the cooperative. Empty means it has never gone out.', null=True),
        ),
    ]
