# Generated by Django 5.2.15 on 2026-09-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0015_onboardingitem_golive_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='ga_measurement_id',
            field=models.CharField(blank=True, help_text='GA4 measurement ID, e.g. "G-XXXXXXXXXX". Leave blank to switch tracking off entirely.', max_length=32, verbose_name='Google Analytics measurement ID'),
        ),
    ]
