# Generated by Django 5.2.15 on 2026-09-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0016_platformprofile_ga_measurement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pay_token',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='psp_reference',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
