# Generated by Django 5.2.15 on 2026-10-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0017_invoice_last_reminder_at_invoice_pay_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='principle_body',
            field=models.TextField(default="Collections settle through licensed payment providers straight into your cooperative's own bank account — we record, reconcile and report on them, and that money never passes through us. The only funds we ever hold are a disbursement float you deposit yourself, when you choose to lend from it: yours to see, to top up, and to withdraw whenever you want it back."),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='principle_title',
            field=models.CharField(default='Ledger first. Custodian only when you ask.', max_length=120),
        ),
    ]
