# Generated by Django 5.2.15 on 2026-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0019_retire_the_never_holds_funds_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL segment: the page is served at /&lt;slug&gt;. Two slugs are wired to routes and must keep their exact spelling — <b>privacy</b> and <b>terms</b>. The privacy one is registered with Google Play, so renaming it breaks the store listing.', max_length=60, unique=True)),
                ('title', models.CharField(help_text='Shown as the page heading and in the footer link.', max_length=200)),
                ('body', models.TextField(help_text='Paste the drafted text. Formatting understood: a blank line starts a new paragraph, <code>## </code> a heading, <code>### </code> a sub-heading, <code>- </code> a bullet, <code>**bold**</code> for bold, and <code>[text](https://…)</code> for a link. Anything else appears as written — HTML is not interpreted, so tags would show as text.')),
                ('effective_date', models.DateField(blank=True, help_text='Shown under the title as the date the policy takes effect. Leave blank to show nothing.', null=True)),
                ('published', models.BooleanField(default=False, help_text='Off until the text is complete. An unpublished document is invisible to visitors and absent from the footer.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the footer. Lower numbers first.')),
            ],
            options={
                'verbose_name': 'Legal / policy document',
                'verbose_name_plural': 'Legal / policy documents',
                'ordering': ['order', 'title'],
            },
        ),
    ]
