# Generated by Django 5.2.15 on 2026-10-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0020_legaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='principle_body',
            field=models.TextField(default="Contributions settle through licensed payment providers straight into your cooperative's own bank account. Every movement is recorded in an append-only double-entry ledger — nothing is edited or deleted, corrections are posted as reversals, and your auditor can follow any figure back to the entry that produced it."),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='principle_title',
            field=models.CharField(default='Every naira, traceable.', max_length=120),
        ),
    ]
