# Generated by Django 5.2.15 on 2026-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0022_principle_band_drops_custody'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownloadTally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'App download tallies',
                'ordering': ['-date', 'platform'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'date'), name='uniq_app_download_per_day')],
            },
        ),
    ]
