# Generated by Django 5.2.15 on 2026-10-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0023_app_download_tally'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['min_members', 'price_monthly', 'name']},
        ),
        migrations.AddField(
            model_name='plan',
            name='price_annual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for a year paid up front. Blank = quoted per society.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_is_from',
            field=models.BooleanField(default=False, help_text='Show the monthly price as a starting price ("From …").'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=8),
        ),
        migrations.AddField(
            model_name='subscription',
            name='monthly_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Negotiated price per billing cycle. Blank = list price.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10),
        ),
    ]
