# Generated by Django 5.2.15 on 2026-10-08 05:21

from django.db import migrations, models


OLD = {
    "pricing_title": "Pricing that follows your size",
    "pricing_intro": ("A monthly subscription per cooperative — not a cut of "
                      "your members' money."),
}
NEW = {
    "pricing_title": "Pricing by member band",
    "pricing_intro": ("One subscription per cooperative, set by how many "
                      "active members you have — never a cut of your members' "
                      "money. Pay annually and get two months free."),
}


def refresh_copy(apps, schema_editor):
    """Replace the pricing copy only where it is still the old default.

    "A monthly subscription" stopped being true once annual billing became the
    standard offer. Copy an admin has written themselves is left alone.
    """
    SiteContent = apps.get_model("platform_admin", "SiteContent")
    for field, old in OLD.items():
        SiteContent.objects.filter(**{field: old}).update(**{field: NEW[field]})


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0025_member_band_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='pricing_intro',
            field=models.TextField(default="One subscription per cooperative, set by how many active members you have — never a cut of your members' money. Pay annually and get two months free."),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='pricing_title',
            field=models.CharField(default='Pricing by member band', max_length=120),
        ),
        migrations.RunPython(refresh_copy, migrations.RunPython.noop),
    ]
