# Generated by Django 5.2.15 on 2026-10-08 07:37

from django.db import migrations, models


import datetime

GROWTH = ["electronic_payouts", "dividends", "savings_plans",
          "custom_branding"]
PLAN_FEATURES = {
    "Starter": [],
    "Growth": GROWTH,
    "Professional": GROWTH + ["custom_domain"],
    "Institutional": GROWTH + ["custom_domain"],
}
GRACE_DAYS = 30


def assign(apps, schema_editor):
    """Give the member-band plans their features; start the grace period.

    Every subscription that exists now keeps every feature for 30 days, so a
    society using, say, the disbursement wallet on Starter is not cut off
    mid-loan the day this ships. After that, features follow the plan.
    """
    Plan = apps.get_model("platform_admin", "Plan")
    Subscription = apps.get_model("platform_admin", "Subscription")

    for name, features in PLAN_FEATURES.items():
        Plan.objects.filter(name=name).update(features=features)

    until = datetime.date.today() + datetime.timedelta(days=GRACE_DAYS)
    Subscription.objects.filter(features_grace_until__isnull=True).update(
        features_grace_until=until)


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0026_pricing_copy_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='extras',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscription',
            name='features_grace_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(assign, migrations.RunPython.noop),
    ]
