# Generated by Django 5.2.15 on 2026-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('contribution', 'Contribution received'), ('statement', 'Statement ready'), ('meeting', 'Meeting reminder'), ('vote', 'Vote open'), ('loan', 'Loan update')], max_length=14),
        ),
    ]
