# Generated by Django 5.2.15 on 2026-10-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('contribution', 'Contribution received'), ('statement', 'Statement ready'), ('meeting', 'Meeting reminder'), ('vote', 'Vote open'), ('loan', 'Loan update'), ('withdrawal', 'Savings withdrawal')], max_length=14),
        ),
    ]
