# Generated by Django 5.2.15 on 2026-07-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=12)),
                ('event_id', models.CharField(max_length=160)),
                ('reference', models.CharField(db_index=True, max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('received', 'Received'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('partial', 'Partial / amount mismatch'), ('duplicate', 'Duplicate settlement'), ('ignored', 'Ignored')], default='received', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='tenants.cooperative')),
                ('matched_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to='contributions.contribution')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_payment_event')],
            },
        ),
        migrations.CreateModel(
            name='ProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=12)),
                ('subaccount_code', models.CharField(max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('connected', models.BooleanField(default=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'subaccount_code'), name='uniq_provider_subaccount')],
            },
        ),
    ]
