# Generated by Django 5.2.15 on 2026-10-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Recorded directly')], max_length=12),
        ),
        migrations.AlterField(
            model_name='provideraccount',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Recorded directly')], max_length=12),
        ),
    ]
