# Generated by Django 5.2.15 on 2026-10-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_bank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provideraccount',
            options={'ordering': ['provider', 'id']},
        ),
    ]
