# Generated by Django 5.2.15 on 2026-10-04 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_internaltransfer'),
        ('payments', '0004_alter_provideraccount_options'),
        ('tenants', '0006_bankdetailchange_bank_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Recorded directly')], default='paystack', max_length=12)),
                ('psp_reference', models.CharField(db_index=True, max_length=120)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_topups', to=settings.AUTH_USER_MODEL)),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_topup', to='ledger.journal')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'psp_reference'), name='uniq_wallet_topup_reference')],
            },
        ),
    ]
