# Generated by Django 5.2.15 on 2026-10-04 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_internaltransfer'),
        ('payments', '0005_wallettopup'),
        ('tenants', '0006_bankdetailchange_bank_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('loan', 'Loan disbursement'), ('wallet', 'Wallet withdrawal'), ('savings', 'Savings withdrawal')], max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('pending', 'Sent — pending'), ('success', 'Paid'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='queued', max_length=10)),
                ('destination_bank_name', models.CharField(blank=True, max_length=120)),
                ('destination_bank_code', models.CharField(blank=True, max_length=10)),
                ('destination_account_no', models.CharField(blank=True, max_length=20)),
                ('destination_account_name', models.CharField(blank=True, max_length=200)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Recorded directly')], default='paystack', max_length=12)),
                ('reference', models.CharField(db_index=True, max_length=120)),
                ('recipient_code', models.CharField(blank=True, max_length=120)),
                ('transfer_code', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='ledger.journal')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payouts', to=settings.AUTH_USER_MODEL)),
                ('reversal_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_payout', to='ledger.journal')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'reference'), name='uniq_payout_reference')],
            },
        ),
    ]
