# Generated by Django 5.2.15 on 2026-10-03 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_joinrequest'),
        ('ledger', '0001_initial'),
        ('savings', '0001_initial'),
        ('tenants', '0005_bankdetailchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('channel', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank transfer')], default='transfer', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('destination_bank_name', models.CharField(blank=True, max_length=120)),
                ('destination_account_no', models.CharField(blank=True, max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('journal', models.OneToOneField(blank=True, help_text='The ledger posting, set when the payout is approved.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal', to='ledger.journal')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='accounts.membership')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
