# Generated by Django 5.2.15 on 2026-07-01 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=12)),
                ('system', models.BooleanField(default=False)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=60)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(help_text='When the underlying event happened (business date).')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journals', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.journal')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.account')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.journal')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounts.membership')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('cooperative', 'code'), name='uniq_account_code_per_coop'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('cooperative', 'reference'), name='uniq_journal_ref_per_coop'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='ledger_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('debit', 0), ('credit__gt', 0)), _connector='OR'), name='ledger_debit_xor_credit'),
        ),
    ]
