# Generated by Django 5.2.15 on 2026-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('registration_no', models.CharField(blank=True, max_length=100)),
                ('coop_type', models.CharField(blank=True, help_text='e.g. multipurpose, thrift & credit, farmers', max_length=100)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('lga', models.CharField(blank=True, max_length=80)),
                ('base_currency', models.CharField(default='NGN', max_length=3)),
                ('tier', models.CharField(choices=[('small', 'Small (50-500)'), ('medium', 'Medium (500-5,000)'), ('large', 'Large / Institutional')], default='small', max_length=10)),
                ('status', models.CharField(choices=[('prospective', 'Prospective'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='prospective', max_length=12)),
                ('brand_color', models.CharField(default='#0b4f3a', max_length=7)),
                ('member_cap', models.PositiveIntegerField(default=5000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
