# Generated by Django 5.2.15 on 2026-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
