# Generated by Django 5.2.15 on 2026-09-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_cooperative_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Square mark for the browser tab and the member PWA icon.', null=True, upload_to='coop_favicons/'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shown in the member app, the console header and at the top of generated statements.', null=True, upload_to='coop_logos/'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='statement_footer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
