# Generated by Django 5.2.15 on 2026-09-24 03:12

from django.db import migrations, models


def backfill_country(apps, schema_editor):
    """Existing societies are all Nigerian — say so explicitly.

    Location was Nigeria-only until this migration, so every row already in
    the table has a Nigerian state and LGA. Leaving country blank would make
    those rows render with the generic "State / Province" labels and lose
    their LGA dropdown. New rows deliberately get no default: a global
    product should not assume where its next customer is.
    """
    Cooperative = apps.get_model('tenants', 'Cooperative')
    Cooperative.objects.filter(country='').update(country='NG')


def unbackfill_country(apps, schema_editor):
    """No-op: the column is dropped on reverse anyway."""


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_cooperative_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code (e.g. NG, KE, GB). Decides what the two fields below are called and whether they offer dropdowns.', max_length=2),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='lga',
            field=models.CharField(blank=True, help_text="LGA / district / city — see the country's labelling.", max_length=80),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='state',
            field=models.CharField(blank=True, help_text="State / province / county — see the country's labelling.", max_length=80),
        ),
        migrations.RunPython(backfill_country, unbackfill_country),
    ]
