# Generated by Django 5.2.15 on 2026-10-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_bankdetailchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetailchange',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bankdetailchange',
            name='previous_bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
