# Generated by Django 5.2.15 on 2026-10-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_bankdetailchange_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='tier',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10),
        ),
    ]
