"""PDF generation for member statements (PRD §6.2 'download it as PDF')."""
from __future__ import annotations

import io
import unicodedata

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from ledger.services import member_statement

GREEN = colors.HexColor("#0b4f3a")
GOLD = colors.HexColor("#d99e2b")


def _ascii(text) -> str:
    """Reduce arbitrary text to characters the base PDF fonts can render.

    The built-in Helvetica font only covers Latin-1, so the Naira sign (₦) and
    accented/African-script glyphs (e.g. 'Ìmọ̀lè') render as blank boxes. We
    transliterate to plain ASCII so nothing disappears — "Ìmọ̀lè" -> "Imole".
    """
    if text is None:
        return ""
    normalized = unicodedata.normalize("NFKD", str(text))
    return normalized.encode("ascii", "ignore").decode("ascii")


def _money(value) -> str:
    # 'N' instead of the ₦ symbol, which the base PDF font cannot render.
    return f"N {value:,.2f}"


def member_statement_pdf(membership) -> bytes:
    """Render a member's dated statement as a PDF and return the bytes."""
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    coop = membership.cooperative
    y = height - 25 * mm

    # Header band
    pdf.setFillColor(GREEN)
    pdf.rect(0, height - 20 * mm, width, 20 * mm, fill=1, stroke=0)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(18 * mm, height - 13 * mm, _ascii(coop.name))
    pdf.setFillColor(GOLD)
    pdf.setFont("Helvetica", 9)
    pdf.drawRightString(width - 18 * mm, height - 13 * mm, "Member Statement")

    pdf.setFillColor(colors.black)
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(18 * mm, y, _ascii(membership.user.full_name))
    pdf.setFont("Helvetica", 9)
    pdf.drawString(18 * mm, y - 5 * mm,
                   f"Member No: {membership.member_no}   "
                   f"Savings balance: {_money(membership.savings_balance)}")

    # Table header
    y -= 16 * mm
    pdf.setFillColor(GREEN)
    pdf.setFont("Helvetica-Bold", 9)
    pdf.drawString(18 * mm, y, "Date")
    pdf.drawString(52 * mm, y, "Description")
    pdf.drawRightString(150 * mm, y, "Amount")
    pdf.drawRightString(190 * mm, y, "Balance")
    pdf.setStrokeColor(GOLD)
    pdf.line(18 * mm, y - 2 * mm, 192 * mm, y - 2 * mm)

    pdf.setFillColor(colors.black)
    pdf.setFont("Helvetica", 9)
    y -= 8 * mm
    for row in member_statement(membership):
        if y < 20 * mm:
            pdf.showPage()
            y = height - 25 * mm
        amount = row["credit"] - row["debit"]
        pdf.drawString(18 * mm, y, row["date"].strftime("%d %b %Y"))
        pdf.drawString(52 * mm, y, _ascii(row["description"] or "")[:45])
        pdf.drawRightString(150 * mm, y, _money(amount))
        pdf.drawRightString(190 * mm, y, _money(row["balance"]))
        y -= 6 * mm

    pdf.setFont("Helvetica-Oblique", 8)
    pdf.setFillColor(colors.grey)
    pdf.drawString(18 * mm, 12 * mm,
                   "Generated by CooperativeOS — figures derive from the "
                   "immutable double-entry ledger.")
    pdf.showPage()
    pdf.save()
    return buffer.getvalue()
