# Generated by Django 5.2.15 on 2026-10-08 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0001_initial'),
        ('ledger', '0002_internaltransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dividenddeclaration',
            name='method',
            field=models.CharField(choices=[('pool', 'Fixed pool shared pro-rata'), ('rate', 'Rate on share capital')], default='pool', max_length=4),
        ),
        migrations.AddField(
            model_name='dividenddeclaration',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dividenddeclaration',
            name='reversal_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_dividend_declarations', to='ledger.journal'),
        ),
        migrations.AddField(
            model_name='dividenddeclaration',
            name='reversal_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dividenddeclaration',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dividenddeclaration',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_dividends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dividenddeclaration',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=8),
        ),
    ]
