# Generated by Django 5.2.15 on 2026-07-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='membership',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='membership',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='membership',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='occupation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='membership',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('id', 'Means of ID'), ('passport', 'Passport photo'), ('proof_of_address', 'Proof of address'), ('form', 'Membership form'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(upload_to='member_documents/')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.membership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
