# Generated by Django 5.2.15 on 2026-10-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
