# Generated by Django 5.2.15 on 2026-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_membership_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='kind',
            field=models.CharField(choices=[('member', 'Member'), ('non_member', 'Non-member')], default='member', max_length=12),
        ),
    ]
