# Generated by Django 5.2.15 on 2026-07-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='minutes',
            field=models.TextField(blank=True, help_text='Recorded after the meeting.'),
        ),
    ]
