# Generated by Django 5.2.15 on 2026-07-27 13:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('tenants', '0002_cooperative_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='channel',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank transfer'), ('psp', 'Online (Paystack)')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='psp_reference',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='confirmed', max_length=10),
        ),
        migrations.CreateModel(
            name='RepaymentInstalment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=8)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalments', to='loans.loan')),
            ],
            options={
                'ordering': ['loan', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('loan', 'sequence'), name='uniq_loan_instalment_sequence')],
            },
        ),
    ]
