# Generated by Django 5.2.15 on 2026-07-27 13:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanrepayment_channel_loanrepayment_psp_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymentinstalment',
            name='interest_component',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='repaymentinstalment',
            name='principal_component',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly interest rate (%), charged on the reducing balance.', max_digits=5),
        ),
    ]
