# Generated by Django 5.2.15 on 2026-07-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_repaymentinstalment_interest_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat interest rate (%) — a one-off charge on the amount borrowed (e.g. 10% of a ₦300,000 loan = ₦30,000), spread evenly across the term. Members repay a fixed amount monthly.', max_digits=5),
        ),
    ]
