# Generated by Django 5.2.15 on 2026-10-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanrepayment_note_alter_loanproduct_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='destination_account_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='destination_bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='destination_bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
