# Generated by Django 5.2.15 on 2026-10-04 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_internaltransfer'),
        ('loans', '0005_loan_destination_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursement_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursed_loans', to='ledger.journal'),
        ),
    ]
