# Generated by Django 5.2.15 on 2026-10-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_internaltransfer'),
        ('loans', '0007_backfill_disbursement_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='reversal_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_loan_repayments', to='ledger.journal'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='reversal_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('reversed', 'Reversed')], default='confirmed', max_length=10),
        ),
    ]
