# Generated by Django 5.2.15 on 2026-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_repayment_reversal'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='application_fee_flat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed application fee, added to any percentage fee.', max_digits=14),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='application_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Application fee as a % of the amount borrowed.', max_digits=5),
        ),
    ]
