# Generated by Django 5.2.15 on 2026-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loan_application_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='non_member_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat interest rate (%) for non-members. Blank = same as members.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='open_to_non_members',
            field=models.BooleanField(default=False),
        ),
    ]
