# Generated by Django 5.2.15 on 2026-10-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_alter_approvalrequest_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='action',
            field=models.CharField(choices=[('loan.approve', 'Approve loan'), ('loan.disburse', 'Disburse loan'), ('dividend.post', 'Post dividend'), ('coop.bank_update', 'Change collection account'), ('savings.withdraw', 'Pay out member savings')], max_length=20),
        ),
    ]
